### PR TITLE
Update config file parameter, default value

### LINKED ISSUE #31: Remove dot from .codecov.yml default
https://github.com/codecov/codecov-bash/issues/281

### LINKED ISSUE #33: Config file not able to be read
It looks like the orb can't find the config file when the path specified is not within the project root. Should me a quick fix to the Orb.

Screen Shot 2020-04-20 at 7 49 50 PM

Here's my config:
```
      - codecov/upload:
          conf: ~/repo/codecov.yml
          file: coverage/.resultset.json
```

### PR DESCRIPTION
**Pull request by dja**
Fixes #31: Update default config file name to `codecov.yml`
Fixes #33: Remove quotes from config file parameter to allow paths outside of `./`

### CODE REVIEW

**Comment by dja** [comment]
@thomasrockhu Can you take a look at this when you get a chance?

**Comment by thomasrockhu** [comment]
Yes! I'll pull this in this weekend or early next week and release.

**Comment by thomasrockhu** [comment]
Apologies @dja, but we are actually deprecating the use of the `-y` flag
https://github.com/codecov/codecov-bash/blob/master/codecov#L929

**Comment by dja** [comment]
Ok @thomasrockhu

**Pull request closed without merging**
