### PR TITLE
feat: allow `file` parameter to be optional

### LINKED ISSUE #6: Make the `file:` parameter optional, or support multiple files.
I've used the codecov-bash for quite a while in my CI jobs like follows:

```
bash <(curl -s https://codecov.io/bash) 
```

I love that CodeCov had created a CircleCI orb, but I'm not happy with the required `file` parameter.

Call me lazy, but I love the original functionality of the codecov script just finding the coverage file on its own. It's one less concern for me when configuring CI.

_Not to mention_ I have many projects which produce coverage reports in multiple formats. One such projects creates clover, junit, and lcov reports. I'm not sure whether any one is better than any other. I am currently arbitrarily choosing one of them. Would CodeCov prefer one of the others? I don't know.

I have also tried to solve this problem like: `file: "coverage/*"`, but only the first matching report is uploaded, rather than _all_ matching reports.

---

So my feature request could be any of the following:

1. The `file:` parameter is no longer required.
2. The `file:` parameter takes an array (or `files:` is introduced).
3. Functionality of `file:` taking a regex is improved upon.

### PR DESCRIPTION
**Pull request by jfairley**
closes #6

### CODE REVIEW

**Comment by thomasrockhu** [comment]
🥇 This looks great, will merge in.  Give us a few hours to update to `1.0.3`

**Comment by jfairley** [comment]
Thanks! I'll give it some time, then give 1.0.3 a go.

**Comment by thomasrockhu** [comment]
@jfairley it should be updated!  Thanks again for the contribution.

**Comment by jfairley** [comment]
I've updated. Works great!

**Pull request merged**
