### PR TITLE
Add "when" condition to upload results

### PR DESCRIPTION
**Pull request by bonkey**
Replicate `when: <<parameters.when>>` from `"Download Codecov Uploader"` step in `"Upload Coverage Results"` and `"Validate Codecov Uploader"`.

### CODE REVIEW

**Comment by bonkey** [comment]
When tests fail the build I'd like to be able to still upload tests results not only download CLI

**Comment by quantizor** [comment]
We need this too

**Comment by quantizor** [comment]
@bonkey looks like this PR needs a rebase too

**Comment by quantizor** [comment]
@thomasrockhu-codecov  /bump

**Comment by quantizor** [comment]
@thomasrockhu-codecov @drazisil-codecov someone please, this is a very annoying bug that is not possible to work around from userland

**Comment by quantizor** [comment]
> @quantizor sorry for the delay here. I've been working on a new release candidate for the Orb (5.0.0) which should remove the necessity for this PR. I'll leave this open in case that doesn't end up working for you.

Ah ok, interesting thank you. Is there an ETA? If not soon, would love to see this land to fix the immediate issue.

**Pull request closed without merging**
