### PR TITLE
Fix shell command issues

### LINKED ISSUE #8: Orb doesn't work in Alpine images
The orb doesn't work if it's run inside an Alpine Linux Docker image. CircleCI is running the script in the orb's `run` step using `/bin/sh` (which in Alpine is the "traditional" version of sh, not bash), and the script is using bash-specific syntax and failing:

```
====>> Upload Coverage Results
  #!/bin/sh -eo pipefail
bash <(curl -s https://codecov.io/bash) \
  -f coverages \
  -n ${CIRCLE_BUILD_NUM} \
  -t ${CODECOV_TOKEN} \
  -y .codecov.yml \
  -F  \
  

/bin/sh: syntax error: unexpected "("
Error: Exited with code 2
Step failed
Error: runner failed
```

### PR DESCRIPTION
**Pull request by teohhanhui**
Fixes #8, #9, #12
Reverts #10
Replaces #16 (sorry @shadowhand, I didn't notice beforehand)

[ShellCheck](https://www.shellcheck.net/) is your friend.

Also fixed wrong indentation introduced in #15 (Indentation is important in YAML ~so everything was completely broken~!)

### CODE REVIEW

**Comment by teohhanhui** [comment]
@thomasrockhu Hope you could take a look at this. :smile:

**Comment by shadowhand** [comment]
@thomasrockhu I recommend #16 over this PR because it is smaller and doesn't have the potential issue with `flag` that this one does.

**Comment by teohhanhui** [comment]
@thomasrockhu You can try it without flags. I've verified that it works correctly (it's already handled in the bash script).

**Comment by teohhanhui** [comment]
@shadowhand #16 does not fix all the same issues.

**Comment by shadowhand** [comment]
@teohhanhui it fixes the critical issue.

**Comment by teohhanhui** [comment]
@shadowhand #16 fixes one issue. Please see the list of issues I've fixed in the OP. The other issues are critical too (for my use case at least).

**Comment by teohhanhui** [comment]
So I must respectfully disagree that #16 is simpler, because further fixes will be required for the other issues. In the end, we'll end up back where we're here.

If you disagree with any changes I've done in this PR, perhaps do a code review please?

**Comment by shadowhand** [comment]
@teohhanhui I don't disagree with any of your fixes. However, when you combine multiple things into a single PR it slows down the process because the whole set has to be accepted or rejected. #16 fixes one critical issue that is blocking usage of Alpine images. Per https://github.com/codecov/codecov-circleci-orb/pull/17#pullrequestreview-245789063, this PR wasn't approved because it did a bunch of things, some of which may require changes.

It is always better to submit PRs that fix **one** issue so that the approval process is faster and the merges more concise and/or easier to revert if necessary.

**Comment by teohhanhui** [comment]
To address the concern with the `-F` (flags), see:

https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L16

https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L289-L296

https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L875

We can see that passing an empty string is perfectly safe, and that's our default value for the `flags` parameter.

**Comment by thomasrockhu** [comment]
@teohhanhui @shadowhand I really appreciate the work you both have done for this repo, and it is developers like you that make these projects survive and thrive.

That said, a lot of progress has been roadblocked by me, in particular, speed to review and merge. I would typically side with @shadowhand's argument that smaller PRs are always preferred, but this PR does do a lot of very good things for the repo, and I would like to unblock our developers.

I'm going to merge this PR in and run a few quick tests around the `flags` parameter. After that, I'm going to release a new version of the orb.

**Pull request merged**
